### ISSUE TITLE
Feature Request Ability to define key to open and close recipe book on demand

### ISSUE THREAD

**Issue by mikeloeven** [CubeSuite/TTMod-RecipeBook#1]
Basically while pressing escape hides the recipe book there is no designated toggle key meaning you need to close and reopen inventory to get it back. If there is a keybind for this function it does not appear to be properly documented on the mod page's instructions for using the mod

**Comment by CubeSuite** [comment]
Thanks for the report! This issue is fixed in an update coming out shortly
