### ISSUE TITLE
filter unknown not working

### ISSUE THREAD

**Issue by robot797** [CubeSuite/TTMod-RecipeBook#3]
the option to filter unknown resepies is not working

**Comment by CubeSuite** [comment]
Could you please provide an example of a recipe that is showing up when it shouldn't? I use the game's vanilla code to determine if a recipe is known, so it should be working fine

**Comment by robot797** [comment]
well I turned it on and off
and it keep showing the cubes even though they are not craftable
I dont have more then drill 4 unlocked
but it keeps showing later drills

I will try to make a picture

**Comment by robot797** [comment]
never mind
I was not paying attention
