### ISSUE TITLE
cant close the recipe book

### ISSUE THREAD

**Issue by robot797** [CubeSuite/TTMod-RecipeBook#4]
so in the crafting menu if you press F11 to close the book
it closes the crafting menu and the book
and when using the book on its own you cant close it at all

**Comment by jrinker03** [comment]
Able to repro the issue.

As a suggestion, perhaps F11 could toggle the recipe book visibility both in the inventory and stand-alone?

**Comment by CubeSuite** [comment]
Fixed this issue in the latest update, you should now use the config option 'Open With Inventory' to choose between the inventory-sync mode and hotkey mode
